# Состояния диалога для ConversationHandler
COMPANY_NAME = 0
COMPANY_INN = 1
SELECT_SERVICE = 2
SELECT_CITY = 3
SELECT_STAGE = 4
UPLOAD_DOCUMENTS = 5
PROCESS_DOCUMENTS = 6
MANUAL_INPUT = 7
ADD_ANOTHER_EMPLOYEE = 8
